name: CI-CD Ansible LAN

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted   # ðŸŸ¢ dÃ¹ng runner trong LAN

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo yum update
          sudo yum install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory ansible/deploy.yml
